### ISSUE TITLE
False positive for error: Invalid Ice Home Directory, in IceBuilder Plugin for Eclipse in Linux

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice-builder-eclipse#2]
In Linux, we get the error "Invalid Ice Home Directory", when setting up the IceBuilder plug in Window-->Preferences->Ice Builder. 
This isn't a real error and we can actually get the system to build properly.

I looked through the source code and think I found the error:

File: ice-builder-eclipse/java/IceBuilderPlugin/src/com/zeroc/icebuilderplugin/internal/Configuration.java
Method: private static String getSliceDirectory(String dir)

This method uses File.pathSeparator (":" on Linux) a number of places, instead of File.separator ("/" on Linux). This causes null to be returned from the method which triggers this false error.

Note: I see File.pathSeparator used many places. It didn't check it out in detail, but I suspect this is probably wrong in at least some of these cases as well.

Originally reported by Stephen Pheiffer on the forums:
https://forums.zeroc.com/discussion/46593/false-positive-for-error-invalid-ice-home-directory-in-icebuilder-plugin-for-eclipse-in-linux

**Comment by externl** [comment]
This was fixed in https://github.com/zeroc-ice/ice-builder-eclipse/commit/ee20838ea872a5205c10f1d5ee78e0cdd4141afd
